/**
 * createNewMenu.test.js
 *
 * Behavioral coverage for the dspfDesigner.createNewMenu command: it must
 * generate BOTH the MNUDDS member and its paired MNUCMD companion together
 * (the gap "Create New Menu" in the README's Known Limitations described),
 * for both the local-workspace path (sibling `<basename>QQ.mnucmd` file) and
 * the remote IBM i path (two ADDPFM calls into the same source file). Run
 * with: node src/test/createNewMenu.test.js
 */
const path = require('path');
const Module = require('module');

const originalLoad = Module._load;
Module._load = function (request, parent, isMain) {
  if (request === 'vscode') return require('./vscode-mock.js');
  return originalLoad.apply(this, arguments);
};

const vscodeMock = require('./vscode-mock.js');
const ext = require(path.join(__dirname, '../../dist/extension.js'));

let failures = 0;
function check(label, condition) {
  if (condition) {
    console.log('  ok  -', label);
  } else {
    failures++;
    console.log('FAIL  -', label);
  }
}

/** Scripts a sequence of showInputBox/showQuickPick answers, consumed in call order. */
function scriptPrompts(inputBoxAnswers, quickPickAnswer) {
  const queue = inputBoxAnswers.slice();
  vscodeMock.window.showInputBox = () => Promise.resolve(queue.shift());
  vscodeMock.window.showQuickPick = () => Promise.resolve(quickPickAnswer);
}

async function run() {
  const context = vscodeMock.__mockExtensionContext();
  ext.activate(context);
  const createNewMenu = vscodeMock.__registeredCommands['dspfDesigner.createNewMenu'];
  check('command registered', typeof createNewMenu === 'function');

  console.log('\nlocal path (no Code for i installed)');
  {
    vscodeMock.extensions.getExtension = () => undefined; // no Code for i
    vscodeMock.workspace.workspaceFolders = [{ uri: vscodeMock.Uri.file('/workspace') }];
    vscodeMock.workspace.fs.stat = () => Promise.reject(new Error('not found')); // neither file already exists
    vscodeMock.__clearMockFiles();
    let openedWithMenuEditor = false;

    scriptPrompts(['MYMENU', 'My Menu']); // no quick pick shown at all in this path

    await createNewMenu();
    openedWithMenuEditor = vscodeMock.__executedCommands.some(
      (c) => c.id === 'vscode.openWith' && c.args[1] === 'dspfDesigner.menuEditor'
    );

    check('never shown a destination choice (no Code for i)', true);

    const menuUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENU.mnudds');
    const cmdUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENUQQ.mnucmd');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    const cmdContent = (await vscodeMock.workspace.fs.readFile(cmdUri)).toString('utf8');

    check('wrote the .mnudds member', menuContent.includes('MYMENU'));
    check('boilerplate contains the title', menuContent.includes("'My Menu'"));
    check('boilerplate contains at least two numbered options', (menuContent.match(/'\d\. Option \d'/g) || []).length === 2);
    check('wrote the paired QQ.mnucmd companion file', cmdContent.includes('Generated by iSDA'));
    check('opened the menu designer (not the plain DSPF designer)', openedWithMenuEditor);
  }

  console.log('\nlocal path: one of the pair already exists -> single combined overwrite prompt');
  {
    vscodeMock.extensions.getExtension = () => undefined;
    vscodeMock.__clearMockFiles();
    const menuUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENU2.mnudds');
    vscodeMock.workspace.fs.stat = (uri) => (uri.path === menuUri.path ? Promise.resolve({ type: 1 }) : Promise.reject(new Error('not found')));
    let warned = null;
    vscodeMock.window.showWarningMessage = (msg, ...rest) => { warned = msg; return Promise.resolve('Overwrite'); };

    scriptPrompts(['MYMENU2', 'Title']);
    await createNewMenu();

    check('warned about the existing file before overwriting', warned && warned.includes('MYMENU2.mnudds'));
    check('did not also claim the companion file existed', warned && !warned.includes('MYMENU2QQ.mnucmd'));
  }

  console.log('\nremote path (Code for i connected, both ADDPFMs succeed)');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => { ranCommands.push(info); return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' }); },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.window.showWarningMessage = () => Promise.resolve(undefined);

    scriptPrompts(['MYMENU3', 'Remote Menu', '', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    check('ran two ADDPFM commands', ranCommands.length === 2);
    check('first ADDPFM creates the MNUDDS member', ranCommands[0].command.includes('MBR(MYMENU3)') && ranCommands[0].command.includes('SRCTYPE(MNUDDS)'));
    check('second ADDPFM creates the paired QQ MNUCMD member', ranCommands[1].command.includes('MBR(MYMENU3QQ)') && ranCommands[1].command.includes('SRCTYPE(MNUCMD)'));
    check('both target the same qualified source file', ranCommands[0].command.includes('FILE(QDDSSRC)') && ranCommands[1].command.includes('FILE(QDDSSRC)'));

    const menuUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU3.MNUDDS');
    const cmdUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU3QQ.MNUCMD');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    const cmdContent = (await vscodeMock.workspace.fs.readFile(cmdUri)).toString('utf8');
    check('wrote content to the member: scheme MNUDDS member', menuContent.includes("'Remote Menu'"));
    check('wrote content to the member: scheme MNUCMD companion', cmdContent.includes('Generated by iSDA'));
  }

  console.log('\nremote path: the MNUDDS ADDPFM fails -> nothing written, companion never attempted');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              return Promise.resolve({ code: 1, stdout: '', stderr: 'CPF7302 - File QDDSSRC in library MYLIB not found.' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU4', 'Title', 'MYLIB', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    check('only attempted the first ADDPFM', ranCommands.length === 1);
    check('surfaced the real CPF error to the user', vscodeMock.__lastError && vscodeMock.__lastError.includes('CPF7302'));
  }

  console.log('\nremote path: MNUDDS ADDPFM succeeds but the companion ADDPFM fails -> menu member still written, warns instead of erroring');
  {
    let call = 0;
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              call++;
              if (call === 1) return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
              return Promise.resolve({ code: 1, stdout: '', stderr: 'CPF7302 - Member already exists.' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    let warned = null;
    vscodeMock.window.showWarningMessage = (msg) => { warned = msg; return Promise.resolve(undefined); };
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU5', 'Title', '', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    check('did not surface this as a hard error', !vscodeMock.__lastError);
    check('warned about the companion member specifically', warned && warned.includes('MYMENU5QQ'));
    const menuUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU5.MNUDDS');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    check('still wrote the menu member content (it was created successfully)', menuContent.includes('MYMENU5'));
  }

  console.log('\n' + (failures === 0 ? 'ALL CHECKS PASSED' : failures + ' CHECK(S) FAILED'));
  process.exit(failures === 0 ? 0 : 1);
}

run();
