/**
 * createNewMenu.test.js
 *
 * Behavioral coverage for the dspfDesigner.createNewMenu command: it must
 * generate BOTH the MNUDDS member and its paired MNUCMD companion together
 * (the gap "Create New Menu" in the README's Known Limitations described),
 * for both the local-workspace path (sibling `<basename>QQ.mnucmd` file) and
 * the remote IBM i path (two ADDPFM calls into the same source file). Run
 * with: node src/test/createNewMenu.test.js
 */
const path = require('path');
const Module = require('module');

const originalLoad = Module._load;
Module._load = function (request, parent, isMain) {
  if (request === 'vscode') return require('./vscode-mock.js');
  return originalLoad.apply(this, arguments);
};

const vscodeMock = require('./vscode-mock.js');
const ext = require(path.join(__dirname, '../../dist/extension.js'));

let failures = 0;
function check(label, condition) {
  if (condition) {
    console.log('  ok  -', label);
  } else {
    failures++;
    console.log('FAIL  -', label);
  }
}

/** Scripts a sequence of showInputBox/showQuickPick answers, consumed in call order. */
function scriptPrompts(inputBoxAnswers, quickPickAnswer) {
  const queue = inputBoxAnswers.slice();
  vscodeMock.window.showInputBox = () => Promise.resolve(queue.shift());
  vscodeMock.window.showQuickPick = () => Promise.resolve(quickPickAnswer);
}

async function run() {
  const context = vscodeMock.__mockExtensionContext();
  ext.activate(context);
  const createNewMenu = vscodeMock.__registeredCommands['dspfDesigner.createNewMenu'];
  check('command registered', typeof createNewMenu === 'function');

  console.log('\nlocal path (no Code for i installed)');
  {
    vscodeMock.extensions.getExtension = () => undefined; // no Code for i
    vscodeMock.workspace.workspaceFolders = [{ uri: vscodeMock.Uri.file('/workspace') }];
    vscodeMock.workspace.fs.stat = () => Promise.reject(new Error('not found')); // neither file already exists
    vscodeMock.__clearMockFiles();
    let openedWithMenuEditor = false;

    scriptPrompts(['MYMENU', 'My Menu']); // no quick pick shown at all in this path

    await createNewMenu();
    openedWithMenuEditor = vscodeMock.__executedCommands.some(
      (c) => c.id === 'vscode.openWith' && c.args[1] === 'dspfDesigner.menuEditor'
    );

    check('never shown a destination choice (no Code for i)', true);

    const menuUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENU.mnudds');
    const cmdUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENUQQ.mnucmd');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    const cmdContent = (await vscodeMock.workspace.fs.readFile(cmdUri)).toString('utf8');

    check('wrote the .mnudds member', menuContent.includes('MYMENU'));
    check('boilerplate contains the title', menuContent.includes("'My Menu'"));
    check('boilerplate contains at least two numbered options', (menuContent.match(/'\d\. Option \d'/g) || []).length === 2);
    check('wrote the paired QQ.mnucmd companion file', cmdContent.includes('Generated by iSDA'));
    check('opened the menu designer (not the plain DSPF designer)', openedWithMenuEditor);
  }

  console.log('\nlocal path: one of the pair already exists -> single combined overwrite prompt');
  {
    vscodeMock.extensions.getExtension = () => undefined;
    vscodeMock.__clearMockFiles();
    const menuUri = vscodeMock.Uri.joinPath(vscodeMock.Uri.file('/workspace'), 'MYMENU2.mnudds');
    vscodeMock.workspace.fs.stat = (uri) => (uri.path === menuUri.path ? Promise.resolve({ type: 1 }) : Promise.reject(new Error('not found')));
    let warned = null;
    vscodeMock.window.showWarningMessage = (msg, ...rest) => { warned = msg; return Promise.resolve('Overwrite'); };

    scriptPrompts(['MYMENU2', 'Title']);
    await createNewMenu();

    check('warned about the existing file before overwriting', warned && warned.includes('MYMENU2.mnudds'));
    check('did not also claim the companion file existed', warned && !warned.includes('MYMENU2QQ.mnucmd'));
  }

  console.log('\nremote path (Code for i connected, source file exists, both ADDPFMs succeed)');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 0, stdout: '', stderr: '' });
              return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.window.showWarningMessage = () => Promise.resolve(undefined);

    scriptPrompts(['MYMENU3', 'Remote Menu', '', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    const addpfmCommands = ranCommands.filter((c) => c.command.startsWith('ADDPFM'));
    check('ran CHKOBJ first (Task M2)', ranCommands[0] && ranCommands[0].command.startsWith('CHKOBJ') && ranCommands[0].command.includes('OBJ(QDDSSRC)'));
    check('no CRTSRCPF offer/run since CHKOBJ said it exists', !ranCommands.some((c) => c.command.startsWith('CRTSRCPF')));
    check('ran two ADDPFM commands', addpfmCommands.length === 2);
    check('first ADDPFM creates the MNUDDS member', addpfmCommands[0].command.includes('MBR(MYMENU3)') && addpfmCommands[0].command.includes('SRCTYPE(MNUDDS)'));
    check('second ADDPFM creates the paired QQ MNUCMD member', addpfmCommands[1].command.includes('MBR(MYMENU3QQ)') && addpfmCommands[1].command.includes('SRCTYPE(MNUCMD)'));
    check('both target the same qualified source file', addpfmCommands[0].command.includes('FILE(QDDSSRC)') && addpfmCommands[1].command.includes('FILE(QDDSSRC)'));

    const menuUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU3.MNUDDS');
    const cmdUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU3QQ.MNUCMD');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    const cmdContent = (await vscodeMock.workspace.fs.readFile(cmdUri)).toString('utf8');
    check('wrote content to the member: scheme MNUDDS member', menuContent.includes("'Remote Menu'"));
    check('wrote content to the member: scheme MNUCMD companion', cmdContent.includes('Generated by iSDA'));
  }

  console.log('\nremote path: Code for i installed but NOT YET ACTIVE this session (bug fix - same as createNewDspf, previously silently skipped the remote option, no error, just a missing choice)');
  {
    const ranCommands = [];
    let activateCalled = false;
    const extStub = {
      isActive: false,
      activate: () => { activateCalled = true; extStub.isActive = true; return Promise.resolve(); },
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 0, stdout: '', stderr: '' });
              return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
            },
          }),
        },
      },
    };
    vscodeMock.extensions.getExtension = () => extStub;
    vscodeMock.__clearMockFiles();
    vscodeMock.window.showWarningMessage = () => Promise.resolve(undefined);

    scriptPrompts(['MYMENU3B', 'Lazily Activated Menu', '', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    check('activate() was called before deciding whether Code for i is usable', activateCalled);
    check('the remote destination choice was still offered (not silently skipped)', ranCommands.length > 0);
    check('ran both ADDPFM commands once activated', ranCommands.filter((c) => c.command.startsWith('ADDPFM')).length === 2);
  }

  console.log('\nremote path: the MNUDDS ADDPFM fails -> nothing written, companion never attempted');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 0, stdout: '', stderr: '' });
              return Promise.resolve({ code: 1, stdout: '', stderr: 'CPF7302 - File QDDSSRC in library MYLIB not found.' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU4', 'Title', 'MYLIB', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    const addpfmCommands = ranCommands.filter((c) => c.command.startsWith('ADDPFM'));
    check('only attempted the first ADDPFM', addpfmCommands.length === 1);
    check('surfaced the real CPF error to the user', vscodeMock.__lastError && vscodeMock.__lastError.includes('CPF7302'));
  }

  console.log('\nremote path: MNUDDS ADDPFM succeeds but the companion ADDPFM fails -> menu member still written, warns instead of erroring');
  {
    let call = 0;
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 0, stdout: '', stderr: '' });
              call++;
              if (call === 1) return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
              return Promise.resolve({ code: 1, stdout: '', stderr: 'CPF7302 - Member already exists.' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    let warned = null;
    vscodeMock.window.showWarningMessage = (msg) => { warned = msg; return Promise.resolve(undefined); };
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU5', 'Title', '', 'QDDSSRC'], { value: 'remote' });
    await createNewMenu();

    check('did not surface this as a hard error', !vscodeMock.__lastError);
    check('warned about the companion member specifically', warned && warned.includes('MYMENU5QQ'));
    const menuUri = new vscodeMock.Uri('member', '/QDDSSRC/MYMENU5.MNUDDS');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    check('still wrote the menu member content (it was created successfully)', menuContent.includes('MYMENU5'));
  }

  console.log('\nremote path (Task M2): source physical file missing (CHKOBJ fails) - offers CRTSRCPF, declining leaves everything untouched');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 1, stdout: '', stderr: '' });
              return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    let warned = null;
    vscodeMock.window.showWarningMessage = (msg) => { warned = msg; return Promise.resolve(undefined); };
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU6', 'Title', '', 'NEWSRCPF'], { value: 'remote' });
    await createNewMenu();

    check('ran CHKOBJ', ranCommands.some((c) => c.command.startsWith('CHKOBJ')));
    check('offered to create it (a warning was shown)', warned && warned.includes('NEWSRCPF'));
    check('declining runs neither CRTSRCPF nor ADDPFM', !ranCommands.some((c) => c.command.startsWith('CRTSRCPF') || c.command.startsWith('ADDPFM')));
    check('nothing written, and no error toast either (a decline is a silent cancel)', !vscodeMock.__lastError);
  }

  console.log('\nremote path (Task M2): source physical file missing - confirming creates it (CRTSRCPF) once, then proceeds to BOTH ADDPFMs');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 1, stdout: '', stderr: '' });
              if (info.command.startsWith('CRTSRCPF')) return Promise.resolve({ code: 0, stdout: '', stderr: '' });
              return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.window.showWarningMessage = () => Promise.resolve('Create it');

    scriptPrompts(['MYMENU7', 'Title', '', 'NEWSRCPF'], { value: 'remote' });
    await createNewMenu();

    const crtsrcpfCommands = ranCommands.filter((c) => c.command.startsWith('CRTSRCPF'));
    const addpfmCommands = ranCommands.filter((c) => c.command.startsWith('ADDPFM'));
    check('ran CRTSRCPF for the missing source file, exactly once (shared by both members)', crtsrcpfCommands.length === 1 && crtsrcpfCommands[0].command.includes('FILE(NEWSRCPF)'));
    check('CRTSRCPF leaves RCDLEN to its own default (*SRC/112) rather than hardcoding one', !crtsrcpfCommands[0].command.includes('RCDLEN'));
    check('proceeded to both ADDPFMs after CRTSRCPF succeeded', addpfmCommands.length === 2);
    check('CRTSRCPF ran before either ADDPFM', ranCommands.indexOf(crtsrcpfCommands[0]) < ranCommands.indexOf(addpfmCommands[0]));

    const menuUri = new vscodeMock.Uri('member', '/NEWSRCPF/MYMENU7.MNUDDS');
    const menuContent = (await vscodeMock.workspace.fs.readFile(menuUri)).toString('utf8');
    check('member content was written', menuContent.includes('MYMENU7'));
  }

  console.log('\nremote path (Task M2): source physical file missing - confirming, but CRTSRCPF itself fails - stops before either ADDPFM');
  {
    const ranCommands = [];
    vscodeMock.extensions.getExtension = () => ({
      isActive: true,
      exports: {
        instance: {
          getConnection: () => ({
            runCommand: (info) => {
              ranCommands.push(info);
              if (info.command.startsWith('CHKOBJ')) return Promise.resolve({ code: 1, stdout: '', stderr: '' });
              if (info.command.startsWith('CRTSRCPF')) return Promise.resolve({ code: 1, stdout: '', stderr: 'CPF3283 - Cannot allocate library.' });
              return Promise.resolve({ code: 0, stdout: 'Member added.', stderr: '' });
            },
          }),
        },
      },
    });
    vscodeMock.__clearMockFiles();
    vscodeMock.window.showWarningMessage = () => Promise.resolve('Create it');
    vscodeMock.__lastError = null;

    scriptPrompts(['MYMENU8', 'Title', '', 'NEWSRCPF'], { value: 'remote' });
    await createNewMenu();

    check('attempted CRTSRCPF', ranCommands.some((c) => c.command.startsWith('CRTSRCPF')));
    check('never reached either ADDPFM after CRTSRCPF failed', !ranCommands.some((c) => c.command.startsWith('ADDPFM')));
    check('surfaced the real CRTSRCPF failure text', vscodeMock.__lastError && vscodeMock.__lastError.includes('CPF3283'));
  }

  console.log('\n' + (failures === 0 ? 'ALL CHECKS PASSED' : failures + ' CHECK(S) FAILED'));
  process.exit(failures === 0 ? 0 : 1);
}

run();
