--Step 1
CALL QSYS2.QCMDEXC('CRTLIB LIB(SDATST) TEXT(''I-SDA I-116 capture'')');
CALL QSYS2.QCMDEXC('CRTSRCPF FILE(SDATST/QDDSSRC) RCDLEN(112)');
CALL QSYS2.QCMDEXC('ADDPFM FILE(SDATST/QDDSSRC) MBR(TESTPF) SRCTYPE(PF)');
CREATE OR REPLACE ALIAS SDATST.QDDSSRC_TESTPF FOR SDATST.QDDSSRC (TESTPF);
DELETE FROM SDATST.QDDSSRC_TESTPF;

INSERT INTO SDATST.QDDSSRC_TESTPF (SRCSEQ, SRCDAT, SRCDTA) VALUES
  (1, 0, '     A          R TESTFMT'),
  (2, 0, '     A            FLDME         10A         CHECK(ME)'),
  (3, 0, '     A            FLDRANGE       5S 0       RANGE(1 99999)'),
  (4, 0, '     A            FLDVALS        1A         VALUES(''A'' ''B'' ''C'')'),
  (5, 0, '     A            FLDCOMP        7P 2       COMP(GT 0)'),
  (6, 0, '     A            FLDCOMPC       3A         COMP(EQ ''XYZ'')'),
  (7, 0, '     A            FLDNEG         7S 2       RANGE(-5.5 100.25)'),
  (8, 0, '     A            FLDM10         6S 0       CHECK(M10)'),
  (9, 0, '     A            FLDVN          9A         CHECK(VN)'),
  (10, 0, '     A            FLDAB          5A         VALUES(''A'' ''B'')'),
  (11, 0, '     A                                      CHECK(AB)'),
  (12, 0, '     A            FLDMSG         5S 0       RANGE(10 20)'),
  (13, 0, '     A                                      CHKMSGID(CPF9897 QSYS/QCPFMSG)'),
  (14, 0, '     A            FLDMSGD        5S 0       VALUES(1 2 3)'),
  (15, 0, '     A                                      CHKMSGID(CPF9897 QCPFMSG &FLDDTA)'),
  (16, 0, '     A            FLDDTA        20A'),
  (17, 0, '     A            FLDMULT        5S 0       RANGE(1 99)'),
  (18, 0, '     A                                      CHECK(ME)'),
  (19, 0, '     A            FLDSGL         7F 2       FLTPCN(*SINGLE)'),
  (20, 0, '     A            FLDDBL        15F 2       FLTPCN(*DOUBLE)'),
  (21, 0, '     A            FLDNONE        5A');

CALL QSYS2.QCMDEXC('CRTPF FILE(SDATST/TESTPF) SRCFILE(SDATST/QDDSSRC) SRCMBR(TESTPF)');

--Step 2
SELECT OS_VERSION, OS_RELEASE FROM SYSIBMADM.ENV_SYS_INFO;
SELECT CURRENT_NUMERIC_VALUE AS QCCSID FROM QSYS2.SYSTEM_VALUE_INFO WHERE SYSTEM_VALUE_NAME = 'QCCSID';

CALL QSYS2.QCMDEXC('DSPFFD FILE(SDATST/TESTPF) OUTPUT(*OUTFILE) OUTFILE(SDATST/FFDOUT)');
SELECT WHFLDI, WHFLDT, WHFLDB, WHFLDD, WHFLDP, WHVCNE, WHCSID, WHECDE
  FROM SDATST.FFDOUT ORDER BY WHFOBO;

--Step 3 dump
CREATE OR REPLACE PROCEDURE SDATST.RTVFD_HEX ()
  LANGUAGE SQL
  RESULT SETS 1
BEGIN
  DECLARE V_RCV     CHAR(32000) FOR BIT DATA DEFAULT X'00';
  DECLARE V_RCVLEN  INTEGER DEFAULT 32000;
  DECLARE V_RTNFILE CHAR(20) DEFAULT ' ';
  DECLARE V_FMT     CHAR(8)  DEFAULT 'FILD0200';
  DECLARE V_FILE    CHAR(20) DEFAULT 'TESTPF    SDATST    ';
  DECLARE V_RECFMT  CHAR(10) DEFAULT '*FIRST    ';
  DECLARE V_OVR     CHAR(1)  DEFAULT '0';
  DECLARE V_SYS     CHAR(10) DEFAULT '*LCL      ';
  DECLARE V_TYPE    CHAR(10) DEFAULT '*EXT      ';
  DECLARE V_ERR     CHAR(16) FOR BIT DATA DEFAULT X'00000010000000000000000000000000';
  DECLARE C1 CURSOR WITH RETURN FOR
    WITH T(N) AS (VALUES 0 UNION ALL SELECT N + 1 FROM T WHERE N < 159)
    SELECT N * 64 AS OFFSET, HEX(SUBSTR(V_RCV, N * 64 + 1, 64)) AS HEXDATA
      FROM T ORDER BY N;

  CALL QSYS.QDBRTVFD(V_RCV, V_RCVLEN, V_RTNFILE, V_FMT, V_FILE, V_RECFMT, V_OVR, V_SYS, V_TYPE, V_ERR);
  OPEN C1;
END;

CALL SDATST.RTVFD_HEX();

--Block A
CREATE OR REPLACE PROCEDURE SDATST.RTVFD_DIAG ()
  LANGUAGE SQL
  RESULT SETS 1
BEGIN
  DECLARE SQLCODE   INTEGER DEFAULT 0;
  DECLARE V_CODE    INTEGER DEFAULT 0;
  DECLARE V_RCV     CHAR(32000) FOR BIT DATA;
  DECLARE V_RCVLEN  INTEGER DEFAULT 32000;
  DECLARE V_RTNFILE CHAR(20) DEFAULT ' ';
  DECLARE V_FMT     CHAR(8)  DEFAULT 'FILD0200';
  DECLARE V_FILE    CHAR(20) DEFAULT 'TESTPF    SDATST    ';
  DECLARE V_RECFMT  CHAR(10) DEFAULT '*FIRST    ';
  DECLARE V_OVR     CHAR(1)  DEFAULT '0';
  DECLARE V_SYS     CHAR(10) DEFAULT '*LCL      ';
  DECLARE V_TYPE    CHAR(10) DEFAULT '*EXT      ';
  DECLARE V_ERR     CHAR(16) FOR BIT DATA DEFAULT X'00000010000000000000000000000000';
  DECLARE C1 CURSOR WITH RETURN FOR
    WITH T(N) AS (VALUES 0 UNION ALL SELECT N + 1 FROM T WHERE N < 127)
    SELECT 'DIAG' AS K, 0 AS OFFSET,
           'SQLCODE=' || CHAR(V_CODE) || ' ERR=' || HEX(V_ERR) ||
           ' RTNFILE=' || TRIM(V_RTNFILE) || ' RCVLEN=' || CHAR(V_RCVLEN) AS HEXDATA
      FROM SYSIBM.SYSDUMMY1
    UNION ALL
    SELECT 'RCV', N * 64, HEX(SUBSTR(V_RCV, N * 64 + 1, 64)) FROM T
    ORDER BY 1, 2;

  SET V_RCV = X'DEADBEEFDEADBEEF';
  CALL QSYS.QDBRTVFD(V_RCV, V_RCVLEN, V_RTNFILE, V_FMT, V_FILE, V_RECFMT, V_OVR, V_SYS, V_TYPE, V_ERR);
  SET V_CODE = SQLCODE;
  OPEN C1;
END;

CALL SDATST.RTVFD_DIAG();

--Block B
CREATE OR REPLACE PROCEDURE SDATST.QDBRTVFD_X (
  INOUT P_RCV     CHAR(32000) FOR BIT DATA,
  INOUT P_RCVLEN  INTEGER,
  INOUT P_RTNFILE CHAR(20),
  INOUT P_FMT     CHAR(8),
  INOUT P_FILE    CHAR(20),
  INOUT P_RECFMT  CHAR(10),
  INOUT P_OVR     CHAR(1),
  INOUT P_SYS     CHAR(10),
  INOUT P_TYPE    CHAR(10),
  INOUT P_ERR     CHAR(16) FOR BIT DATA)
  LANGUAGE CL
  PARAMETER STYLE GENERAL
  NO SQL
  EXTERNAL NAME 'QSYS/QDBRTVFD';

CREATE OR REPLACE PROCEDURE SDATST.RTVFD_DIAG2 ()
  LANGUAGE SQL
  RESULT SETS 1
BEGIN
  DECLARE SQLCODE   INTEGER DEFAULT 0;
  DECLARE V_CODE    INTEGER DEFAULT 0;
  DECLARE V_RCV     CHAR(32000) FOR BIT DATA;
  DECLARE V_RCVLEN  INTEGER DEFAULT 32000;
  DECLARE V_RTNFILE CHAR(20) DEFAULT ' ';
  DECLARE V_FMT     CHAR(8)  DEFAULT 'FILD0200';
  DECLARE V_FILE    CHAR(20) DEFAULT 'TESTPF    SDATST    ';
  DECLARE V_RECFMT  CHAR(10) DEFAULT '*FIRST    ';
  DECLARE V_OVR     CHAR(1)  DEFAULT '0';
  DECLARE V_SYS     CHAR(10) DEFAULT '*LCL      ';
  DECLARE V_TYPE    CHAR(10) DEFAULT '*EXT      ';
  DECLARE V_ERR     CHAR(16) FOR BIT DATA DEFAULT X'00000010000000000000000000000000';
  DECLARE C1 CURSOR WITH RETURN FOR
    WITH T(N) AS (VALUES 0 UNION ALL SELECT N + 1 FROM T WHERE N < 127)
    SELECT 'DIAG' AS K, 0 AS OFFSET,
           'SQLCODE=' || CHAR(V_CODE) || ' ERR=' || HEX(V_ERR) ||
           ' RTNFILE=' || TRIM(V_RTNFILE) || ' RCVLEN=' || CHAR(V_RCVLEN) AS HEXDATA
      FROM SYSIBM.SYSDUMMY1
    UNION ALL
    SELECT 'RCV', N * 64, HEX(SUBSTR(V_RCV, N * 64 + 1, 64)) FROM T
    ORDER BY 1, 2;

  SET V_RCV = X'DEADBEEFDEADBEEF';
  CALL SDATST.QDBRTVFD_X(V_RCV, V_RCVLEN, V_RTNFILE, V_FMT, V_FILE, V_RECFMT, V_OVR, V_SYS, V_TYPE, V_ERR);
  SET V_CODE = SQLCODE;
  OPEN C1;
END;

CALL SDATST.RTVFD_DIAG2();

--Block C 

CREATE OR REPLACE PROCEDURE QTEMP.QDBRTVFD_X (
  INOUT P_RCV     CHAR(32000) FOR BIT DATA,
  INOUT P_RCVLEN  INTEGER,
  INOUT P_RTNFILE CHAR(20),
  INOUT P_FMT     CHAR(8),
  INOUT P_FILE    CHAR(20),
  INOUT P_RECFMT  CHAR(10),
  INOUT P_OVR     CHAR(1),
  INOUT P_SYS     CHAR(10),
  INOUT P_TYPE    CHAR(10),
  INOUT P_ERR     CHAR(16) FOR BIT DATA)
  LANGUAGE CL
  PARAMETER STYLE GENERAL
  NO SQL
  EXTERNAL NAME 'QSYS/QDBRTVFD';

CREATE OR REPLACE PROCEDURE QTEMP.RTVFD_DIAG3 ()
  LANGUAGE SQL
  RESULT SETS 1
BEGIN
  DECLARE SQLCODE   INTEGER DEFAULT 0;
  DECLARE V_CODE    INTEGER DEFAULT 0;
  DECLARE V_RCV     CHAR(32000) FOR BIT DATA;
  DECLARE V_RCVLEN  INTEGER DEFAULT 32000;
  DECLARE V_RTNFILE CHAR(20) DEFAULT ' ';
  DECLARE V_FMT     CHAR(8)  DEFAULT 'FILD0200';
  DECLARE V_FILE    CHAR(20) DEFAULT 'TESTPF    SDATST    ';
  DECLARE V_RECFMT  CHAR(10) DEFAULT '*FIRST    ';
  DECLARE V_OVR     CHAR(1)  DEFAULT '0';
  DECLARE V_SYS     CHAR(10) DEFAULT '*LCL      ';
  DECLARE V_TYPE    CHAR(10) DEFAULT '*EXT      ';
  DECLARE V_ERR     CHAR(16) FOR BIT DATA DEFAULT X'00000010000000000000000000000000';
  DECLARE C1 CURSOR WITH RETURN FOR
    SELECT 'SQLCODE=' || CHAR(V_CODE) || ' ERR=' || HEX(V_ERR) || ' HEAD=' || HEX(SUBSTR(V_RCV, 1, 16)) AS DIAG
      FROM SYSIBM.SYSDUMMY1;
  SET V_RCV = X'DEADBEEFDEADBEEF';
  CALL QTEMP.QDBRTVFD_X(V_RCV, V_RCVLEN, V_RTNFILE, V_FMT, V_FILE, V_RECFMT, V_OVR, V_SYS, V_TYPE, V_ERR);
  SET V_CODE = SQLCODE;
  OPEN C1;
END;

CALL QTEMP.RTVFD_DIAG3();

CALL QSYS2.QCMDEXC('DLTLIB LIB(SDATST)');