import json, datetime

data = {
    "meta": {
        "title": "iSDA Keyword Index",
        "purpose": "Full inventory of DDS keywords iSDA's visual designer exposes, organized by level and UI category, for comparison against IBM i SDA's own screens and to power quick keyword search/navigation.",
        "generated": datetime.date.today().isoformat(),
        "source_repo": "github.com/Manojkumar-Dharma/I-SDA",
        "notes": [
            "Extracted directly from src/webviewClientHelpers.js and src/dspfWriter.js (ground truth), cross-checked against docs/sda-reference/screens/* (real SDA reference screenshots) during the A1/A2 audit.",
            "'category' matches the exact picker tab/accordion label shown in iSDA's own UI.",
            "'sharedWith' lists other record/field types that reuse the same panel (e.g. R1's 8 panels are reused by SFLCTL, WINDOW, PULLDOWN, MNUBAR, etc. - see docs/sda-reference/PICKER-SCREENS-PLAN.md).",
            "Repeatable/multi-instance keywords (CHECK, ERRMSG/ERRMSGID, SFLMSG/SFLMSGID, record indicator keywords) are listed once with 'repeatable: true' rather than once per sub-code.",
            "This file is generated by hand from a point-in-time audit (2026-09-05) - it is NOT auto-synced with the codebase. Re-run the same extraction if keywords are added/changed."
        ]
    },
    "levels": []
}

def lvl(name, description):
    d = {"level": name, "description": description, "categories": []}
    data["levels"].append(d)
    return d

def cat(level, name, description, keywords, sharedWith=None, screenshotDir=None):
    level["categories"].append({
        "category": name,
        "description": description,
        "sharedWith": sharedWith or [],
        "screenshotDir": screenshotDir,
        "keywords": keywords
    })

def kw(name, desc, params="", repeatable=False):
    return {"keyword": name, "description": desc, "parameters": params, "repeatable": repeatable}

# ============================== FILE LEVEL ==============================
file_lvl = lvl("file", "File-level keywords - apply to the whole DSPF, set on the file's own top-level keyword list. One picker: 'Select File Keywords' (Task F1, 9 categories).")

cat(file_lvl, "General", "File-wide behavior flags plus REF/PASSRCD/TEXT.", [
    kw("INVITE", "Invite devices for later read"),
    kw("ALWGPH", "Allow graphics"),
    kw("MSGALARM", "Sound alarm on messages"),
    kw("INDARA", "Use a separate indicator area instead of field-level indicators"),
    kw("USRDSPMGT", "Manage display in S/36 mode"),
    kw("CHECK", "Allow blanks (AB) / move cursor right-left top-bottom (RLTB) / right to left (RL)", "AB | RLTB | RL", repeatable=True),
    kw("DSPRL", "Right to left processing"),
    kw("CHGINPDFT", "Change input field defaults", "attribute codes, e.g. HI RI CS BL UL LC ME MF FE"),
    kw("ENTFLDATR", "Default attribute for entry fields (referenced via entFldAtrHtml, shared with record-level)"),
    kw("ERRSFL", "Write error messages to a message subfile"),
    kw("REF", "Reference database file for field attributes", "library / record"),
    kw("PASSRCD", "Record to pass unformatted data to/from", "record name"),
    kw("TEXT", "Documentation text - no compiled/runtime effect", "'quoted text'"),
], screenshotDir="screens/file-level/01-general-keywords")

cat(file_lvl, "Indicator", "Screen-control indicator keywords (CA/CF command keys have their own separate Command Keys panel).", [
    kw("CLEAR", "Indicator to clear the display", "10-99, or 01-99"),
    kw("HOME", "Indicator for the Home key", "10-99"),
    kw("PAGEDOWN", "Indicator for Page down (legacy alias ROLLUP recognized)", "10-99"),
    kw("PAGEUP", "Indicator for Page up (legacy alias ROLLDOWN recognized)", "10-99"),
    kw("HELP", "Indicator for the Help key", "10-99"),
    kw("HLPRTN", "Indicator for Help return", "10-99"),
    kw("VLDCMDKEY", "Indicator for an invalid command key", "10-99"),
    kw("INDTXT", "Descriptive text for an indicator", "indicator 'text'", repeatable=True),
], screenshotDir="screens/file-level/02-indicator-keywords")

cat(file_lvl, "Print", "Print key and system-print handling.", [
    kw("PRINT", "Enable the Print key", "response indicator (optional, if program handles it)"),
    kw("PRTFILE", "System handles print via this print file", "file / library"),
    kw("OPENPRT", "Leave print file open until display file is closed"),
], screenshotDir="screens/file-level/03-print-keywords")

cat(file_lvl, "Help", "File-wide online help behavior.", [
    kw("HLPPNLGRP", "Help text supplied by a UIM panel group", "panel-group-name library module-name"),
    kw("HLPSCHIDX", "Enable a search index for help", "search-index-object library"),
    kw("HLPFULL", "Full-screen help text"),
    kw("HLPTITLE", "Help title text", "'quoted text'"),
], screenshotDir="screens/file-level/04-help-keywords")

cat(file_lvl, "Display Sizes", "DSPSIZ (up to 2 sizes) plus each size's own message line.", [
    kw("DSPSIZ", "Supported display sizes (24x80 / 27x132), in priority order", "rows cols [*DS3|*DS4] ..."),
    kw("MSGLOC", "Message line row, primary and per-size-conditioned", "line number, or conditioned by *DS3/*DS4"),
], screenshotDir="screens/file-level/05-display-sizes")

cat(file_lvl, "DBCS Conversion", "Double-byte character set conversion key.", [
    kw("IGCCNV", "DBCS conversion command-function key and line", "CF01-CF24, line 1-24"),
], screenshotDir="screens/file-level/06-dbcs-conversion")

cat(file_lvl, "Alternate", "Alternate key assignments for Help/Page.", [
    kw("ALTHELP", "Alternative help key", "CA01-CA24"),
    kw("ALTPAGEUP", "Alternative page-up key", "CF01-CF24"),
    kw("ALTPAGEDWN", "Alternative page-down key", "CF01-CF24"),
], screenshotDir="screens/file-level/07-alternate-keywords")

cat(file_lvl, "Window Border", "Default border styling for every WINDOW on the file (same panel record-level Window reuses).", [
    kw("WDWBORDER", "Default window border color/display-attributes/characters for the whole file", "(*COLOR c)(*DSPATR a)(*CHAR 'cccccccc')"),
], sharedWith=["record: WINDOW", "record: WNDSFCTL", "record: PULLDOWN"], screenshotDir="screens/file-level/08-window-border")

cat(file_lvl, "Menu-bar", "File-wide menu-bar switch/cancel keys.", [
    kw("MNUBARSW", "Menu-bar switch key", "indicator, CA key 01-24"),
    kw("MNUCNL", "Menu-cancel key", "indicator, CA key 01-24, response-indicator 01-99"),
], sharedWith=["record: MNUBAR"], screenshotDir="screens/file-level/09-menu-bar-keywords")

cat(file_lvl, "Command Keys", "CAxx/CFxx function-key assignments (own dedicated panel, shared verbatim across file/record levels).", [
    kw("CA01-CA24", "Command Attention key (no field/record I/O)", "indicator, response-indicator, 'text'", repeatable=True),
    kw("CF01-CF24", "Command Function key (returns to program)", "indicator, response-indicator, 'text'", repeatable=True),
], sharedWith=["record: General (all types)"])

# ============================== RECORD LEVEL - BASE (R1) ==============================
rec_lvl = lvl("record", "Record-level keywords - apply to one record format. R1's 8-panel 'Select Record Keywords' picker is the base set, reused (in full or narrowed subsets) by every record type.")

cat(rec_lvl, "General", "Record-wide behavior flags plus command-keys entry point, TEXT, ALTNAME.", [
    kw("INZRCD", "Write record before issuing read if not already on display"),
    kw("KEEP", "Keep record on display when file closes"),
    kw("ASSUME", "Assume record is already on display"),
    kw("ALWROL", "Allow rolling of lines"),
    kw("RETKEY", "Retain CLEAR/HELP/HOME/ROLL keys"),
    kw("RETCMDKEY", "Retain CFnn/CAnn command keys"),
    kw("CHGINPDFT", "Change input field defaults", "attribute codes"),
    kw("MNUBARDSP", "Menu-bar display", "parameters (optional)"),
    kw("ENTFLDATR", "Default attribute for entry fields in this record"),
    kw("RTNCSRLOC", "Return cursor location to these hidden fields", "row field, column field"),
    kw("TEXT", "Documentation text - no compiled/runtime effect", "'quoted text'"),
    kw("ALTNAME", "Alternative record name for program-described-file I/O", "'alternative-name'"),
], sharedWith=["RECORD", "SFLCTL", "SFLMSGCTL", "WINDOW", "WNDSFCTL", "PULLDOWN", "PDNSFLCTL", "MNUBAR", "USRDFN (4-of-8 subset)"], screenshotDir="screens/record-level/base-record-keywords/general")

cat(rec_lvl, "Indicator", "Repeatable, independently-conditioned screen-control indicator instances (CA/CF command keys have their own panel).", [
    kw("CLEAR", "Indicator to clear the display", "10-99", repeatable=True),
    kw("PAGEDOWN", "Indicator for Page down (alias ROLLUP)", "10-99", repeatable=True),
    kw("PAGEUP", "Indicator for Page up (alias ROLLDOWN)", "10-99", repeatable=True),
    kw("HOME", "Indicator for the Home key", "10-99", repeatable=True),
    kw("HELP", "Indicator for the Help key", "10-99", repeatable=True),
    kw("HLPRTN", "Indicator for Help return", "10-99", repeatable=True),
    kw("VLDCMDKEY", "Indicator for an invalid command key", "10-99", repeatable=True),
    kw("SETOF", "Set indicator(s) off when this record is used", "indicator, up to 3", repeatable=True),
    kw("CHANGE", "Return-this-record-on-changed-field indicator", "indicator", repeatable=True),
    kw("INDTXT", "Descriptive text for an indicator", "indicator 'text'", repeatable=True),
], sharedWith=["RECORD", "SFLCTL", "WINDOW", "PULLDOWN", "MNUBAR"], screenshotDir="screens/record-level/base-record-keywords/indicator")

cat(rec_lvl, "Application help", "SDA shows this as its own screen (Help number N of M / Next help number); iSDA does not model it as a record-level tab - those 4 keywords are Help-SPECIFICATION-level (a separate H-line DDS entry), not record-level, and live on each Help entry's own properties instead.", [
    kw("HLPPNLGRP", "Help text supplied by a UIM panel group (Help-specification level, not record-level)", "panel-group-name library module-name"),
    kw("HLPEXCLD", "Exclude area from help text (Help-specification level)"),
    kw("HLPBDY", "Help boundary area (Help-specification level)"),
    kw("HLPARA", "Help specification area (Help-specification level)"),
], screenshotDir="screens/record-level/base-record-keywords/application-help")

cat(rec_lvl, "Help", "Record-level online help.", [
    kw("HLPCLR", "Clear previous help text records"),
    kw("HLPSEQ", "Sequence of help text records", "help group name, sequence number 0-99"),
    kw("HLPCMDKEY", "Return command key from help"),
    kw("HLPTITLE", "Help title text", "'quoted text'"),
], sharedWith=["RECORD", "SFLCTL", "WINDOW", "PULLDOWN", "MNUBAR"], screenshotDir="screens/record-level/base-record-keywords/help")

cat(rec_lvl, "Output", "Output-operation behavior for this record.", [
    kw("BLINK", "Blink the cursor"),
    kw("ALARM", "Sound the alarm"),
    kw("MSGALARM", "Sound alarm on messages"),
    kw("LOCK", "Do not unlock keyboard"),
    kw("LOGOUT", "Write record to job log"),
    kw("INVITE", "Invite devices for later read"),
    kw("ALWGPH", "Allow graphics"),
    kw("FRCDTA", "Force data out before buffer is full"),
    kw("DSPMOD", "Use alternate display mode", "display name, e.g. *DS3"),
    kw("CSRLOC", "Hidden fields carrying cursor position for output", "row field, column field"),
    kw("SLNO", "Start line number", "*VAR, or line number"),
    kw("CLRL", "Clear previous display from this line down", "line number, or nn ..."),
], screenshotDir="screens/record-level/base-record-keywords/output")

cat(rec_lvl, "Input", "Input-operation behavior for this record.", [
    kw("LOGINP", "Write record to job log"),
    kw("UNLOCK", "Unlock keyboard after input operation", "*ERASE, *MDTOFF (optional flags)"),
    kw("GETRETAIN", "Retain data on display if UNLOCK specified"),
    kw("RETLCKSTS", "Retain LOCK status on next read", "indicators (optional)"),
    kw("CHECK", "Allow blanks (AB) / move cursor right-to-left (RL)", "AB | RL"),
    kw("RTNDTA", "Return same input data on next read"),
], screenshotDir="screens/record-level/base-record-keywords/input")

cat(rec_lvl, "Overlay", "Overlay-without-erasing behavior.", [
    kw("OVERLAY", "Overlay without erasing"),
    kw("PUTRETAIN", "Retain data on re-display"),
    kw("PROTECT", "Protect all input fields"),
    kw("PUTOVR", "Activate OVRDTA and OVRATR"),
    kw("OVRDTA", "Override data"),
    kw("OVRATR", "Override attribute"),
    kw("INZINP", "Initialize input fields"),
    kw("MDTOFF", "Reset all modified data tags", "*UNPR or *ALL (optional)"),
    kw("ERASEINP", "Erase all input fields", "*MDTON or *ALL (optional)"),
    kw("ERASE", "Erase all records below this one"),
], screenshotDir="screens/record-level/base-record-keywords/overlay")

cat(rec_lvl, "Print", "Print key and system-print handling (record-level).", [
    kw("PRINT", "Enable the Print key", "response indicator (optional)"),
    kw("PRTFILE", "System handles print via this print file", "file / library"),
], screenshotDir="screens/record-level/base-record-keywords/print")

# ============================== RECORD LEVEL - VARIANTS ==============================
cat(rec_lvl, "Subfile - General (SFL)", "SFL detail record's own general flags (reuses the record General panel's Y=Yes rows shown on this screen).", [
    kw("SFLNXTCHG", "Return this record on read next changed", "indicators"),
    kw("LOGOUT", "Write record to job log"),
    kw("LOGINP", "Write record to job log (input)"),
    kw("KEEP", "Keep records on display when closing the file"),
    kw("CHECK", "Allow blanks (AB) / move cursor right to left (RL)", "AB | RL"),
    kw("CHGINPDFT", "Change input defaults", "select parameters"),
], sharedWith=["WNDSFL", "PULDWNSFL"], screenshotDir="screens/record-level/subfile-sfl/general")

cat(rec_lvl, "Subfile - Indicator (SFL)", "Repeatable indicator instances specific to the subfile detail record.", [
    kw("INDTXT", "Descriptive text for an indicator", "indicator 'text'", repeatable=True),
    kw("SETOF", "Set indicator(s) off", "indicator", repeatable=True),
    kw("CHANGE", "Return-on-changed indicator", "indicator", repeatable=True),
], sharedWith=["WNDSFL", "PULDWNSFL"], screenshotDir="screens/record-level/subfile-sfl/indicator")

cat(rec_lvl, "Subfile keywords (SFLRCDNBR/SFLROLVAL)", "Field-level keywords for a field within an SFL/SFLCTL record (numeric fields only, Task D3).", [
    kw("SFLRCDNBR", "Subfile record number field", "*TOP, or a numeric field"),
    kw("SFLROLVAL", "Number of records to roll", "value or field"),
], screenshotDir="screens/record-level/subfile-sfl/subfile-keywords")

cat(rec_lvl, "Subfile Control - General (SFLCTL)", "SFLCTL's own record-level control keywords, plus the linkage to its SFL.", [
    kw("SFLCTL", "This is a subfile control record, naming its related SFL", "subfile record name"),
    kw("SFLCSRRRN", "Subfile cursor relative record number field", "name"),
    kw("SFLMODE", "Subfile mode field", "name"),
    kw("SFLDSP", "Display subfile records"),
    kw("SFLDSPCTL", "Display control record"),
    kw("SFLINZ", "Initialize subfile fields"),
    kw("SFLDLT", "Delete subfile area"),
    kw("SFLCLR", "Clear subfile records"),
    kw("SFLEND", "Indicate more records exist", "*MORE | *SCRBAR"),
    kw("SFLRNA", "Record not active"),
    kw("SFLDROP", "Subfile initially truncated"),
    kw("SFLFOLD", "Subfile initially folded"),
    kw("SFLENTER", "Use Enter key instead of a command key to process the subfile"),
], sharedWith=["WNDSFCTL", "PDNSFLCTL"], screenshotDir="screens/record-level/subfile-control-sflctl/general")

cat(rec_lvl, "Subfile Control - Display Layout", "Subfile sizing.", [
    kw("SFLSIZ", "Number of records in the subfile", "number [, display-size]"),
    kw("SFLPAG", "Number of records per display page", "number [, display-size]"),
    kw("SFLLIN", "Spaces between subfile records", "number"),
], sharedWith=["WNDSFCTL", "PDNSFLCTL"], screenshotDir="screens/record-level/subfile-control-sflctl/display-layout")

cat(rec_lvl, "Subfile Control - Subfile Messages", "Message text/id lines shown with the subfile.", [
    kw("SFLMSG", "Subfile message text", "indicators 'text' more-indicator", repeatable=True),
    kw("SFLMSGID", "Subfile message by message ID", "msgid file library indicator name", repeatable=True),
], sharedWith=["WNDSFCTL", "PDNSFLCTL"], screenshotDir="screens/record-level/subfile-control-sflctl/subfile-messages")

cat(rec_lvl, "Window control (WNDSFCTL general screen)", "Two record-level flags shown alongside WINDOW/WDWBORDER on SDA's WNDSFCTL general screen.", [
    kw("RMVWDW", "Remove existing windows before this record is displayed", "indicators (optional)"),
    kw("USRRSTDSP", "Program handles display restore around this window", "indicators (optional)"),
], screenshotDir="screens/record-level/window-subfile-control-wndsfctl/general")

cat(rec_lvl, "Subfile Message record (SFLMSG record type) - Message Record", "The SFLMSG record's own message-linking keywords (distinct from SFLCTL's Subfile Messages panel above).", [
    kw("SFLMSGRCD", "Line number for the first message, conditioned by display size, with roll", "1-27 [, *DS3/*DS4] [, +/-]"),
    kw("SFLMSGKEY", "Message ID field (program builds queue one message at a time)", "field name"),
    kw("SFLPGMQ", "Program message queue field, or generate a 276-byte field", "field name | Y=Yes"),
], screenshotDir="screens/record-level/subfile-message-sflmsg/message-record")

cat(rec_lvl, "Window Parameters", "WINDOW keyword in all 3 forms (referenced / default-start / explicit start+size), plus MSGLIN and RSTCSR sub-parameters.", [
    kw("WINDOW", "Window definition or reference to another window", "referenced-window-name | start-line start-col lines cols [*NOMSGLIN] [*RSTCSR|*NORSTCSR]"),
], sharedWith=["WNDSFCTL", "PULLDOWN"], screenshotDir="screens/record-level/window/window-parameters-size-roll")

cat(rec_lvl, "Border Parameters / Border Color / Border Display Attributes / Border Characters", "WDWBORDER's 3 groups (COLOR, DSPATR, CHAR), navigated via one sub-menu, shared with the file-level Window Border default.", [
    kw("WDWBORDER", "Window border color / display attributes / 8-position border characters", "(*COLOR c)(*DSPATR a1 a2 ...)(*CHAR 'cccccccc')"),
], sharedWith=["file-level Window Border", "MNUBAR record's MNUBARSEP (same *CHAR/*COLOR/*DSPATR group shape)"], screenshotDir="screens/record-level/window/border-parameters")

cat(rec_lvl, "Pull-Down - General", "PULLDOWN record's own keyword plus its window border.", [
    kw("PULLDOWN", "This record is a pull-down, with selection-indicator/cursor-restriction sub-flags", "*SLTIND *RSTCSR (optional)"),
    kw("WDWBORDER", "Pull-down border styling"),
], screenshotDir="screens/record-level/pulldown-puldwn/general")

cat(rec_lvl, "Menu-Bar record - General", "MNUBAR record's own keywords.", [
    kw("MNUBAR", "This record is a menu bar, with an optional display separator", "Y | display-separator"),
    kw("MNUBARDSP", "Menu-bar display, optionally naming a pull-down input field", "field name (optional)"),
    kw("MNUBARSW", "Menu-bar switch key", "indicators, CA key 01-24"),
    kw("MNUCNL", "Menu-cancel key", "indicators, CA key 01-24, response-indicator 01-99"),
], screenshotDir="screens/record-level/menu-bar-record-mnubar/general")

cat(rec_lvl, "Menu-Bar record - Menu-Bar Display Keywords", "Repeatable conditioned MNUBARDSP instances.", [
    kw("MNUBARDSP", "Menu-bar display, conditioned per instance", "indicators, pull-down input field name", repeatable=True),
], screenshotDir="screens/record-level/menu-bar-record-mnubar/menu-bar-display-keywords")

# ============================== FIELD LEVEL ==============================
fld_lvl = lvl("field", "Field-level keywords - apply to one field or constant. D1 (character) is the base set; numeric/constant/menu-bar-choice add or narrow from it.")

cat(fld_lvl, "Colors", "COLOR keyword, up to 7 conditioned instances.", [
    kw("COLOR", "Field color", "BLU | GRN | PNK | RED | TRQ | WHT | YLW", repeatable=True),
], screenshotDir="screens/field-level/character/colors")

cat(fld_lvl, "Display Attributes", "DSPATR keyword, up to 7 conditioned instances, 11 supported values.", [
    kw("DSPATR", "Display attribute(s)", "HI RI CS BL ND UL PC SP UH RE MDT (each independently toggleable)", repeatable=True),
], screenshotDir="screens/field-level/character/display-attributes")

cat(fld_lvl, "Keying Options", "CHECK-family keying restrictions plus the type-gated KEYBRD keyboard-shift attribute.", [
    kw("CHECK", "Mandatory entry (ME) / auto record advance (ER) / mandatory fill (MF) / field exit required (FE) / right-adjust blank fill (RB) / right-adjust zero fill (RZ) / move cursor right-to-left (RL) / lowercase allowed (LC)", "ME | ER | MF | FE | RB | RZ | RL | LC", repeatable=True),
    kw("KEYBRD", "Keyboard shift attribute - value list depends on the field's data type (Task L59: character gets N/A/X/W/I/D/M/J/O/E/G, numeric gets S/N/Y/I/D)", "one letter, type-dependent"),
], screenshotDir="screens/field-level/character/keying-options")

cat(fld_lvl, "Validity Check", "RANGE/COMP/VALUES value-checking plus CHECK-family self-check codes and CHKMSGID.", [
    kw("RANGE", "Valid value range", "low high"),
    kw("COMP", "Valid value comparison", "operator value"),
    kw("VALUES", "Valid value list", "value list"),
    kw("CHECK", "Name-extended field (VNE) / name field (VN) / allow blanks (AB) / modulus-10 self-check (M10/M10F) / modulus-11 self-check (M11/M11F)", "VNE | VN | AB | M10 | M10F | M11 | M11F", repeatable=True),
    kw("CHKMSGID", "Override the system-supplied validity-error message", "message-id [library/]message-file [&message-data-field]"),
], screenshotDir="screens/field-level/character/validity-check")

cat(fld_lvl, "Input Keywords", "Duplication/blank/change handling on input.", [
    kw("BLANKS", "Response for blank input", "response indicator, text"),
    kw("CHANGE", "Response for changed input", "response indicator, text"),
    kw("DUP", "Duplication handled by user program", "response indicator, text"),
    kw("CHGINPDFT", "Change input defaults", "select parameters"),
], screenshotDir="screens/field-level/character/input-keywords")

cat(fld_lvl, "General", "Documentation/reference/default-value keywords.", [
    kw("ALIAS", "Alternative field name"),
    kw("INDTXT", "Descriptive text for an indicator", "indicator 'text'"),
    kw("DFT", "Default value", "'text or value'"),
    kw("DFTVAL", "Default value (conditioned)", "'text or value'", repeatable=True),
    kw("CNTFLD", "Continued field", "field name (character fields only)"),
    kw("FLDCSRPRG", "Field cursor progression order"),
    kw("PUTRETAIN", "Retain field on display"),
    kw("OVRDTA", "Override data"),
    kw("OVRATR", "Override attributes"),
    kw("CHRID", "Translate characters (graphic character set/code page)"),
    kw("IGCALTTYP", "Alter IGC (DBCS) type (character fields only)"),
    kw("NOCCSID", "No coded character set ID"),
], screenshotDir="screens/field-level/character/general")

cat(fld_lvl, "Database Reference", "REFFLD-based field-definition reference plus override/ignore flags.", [
    kw("REFFLD", "Reference field for attributes (implemented via the separate 'Resolve Referenced Field via Code for i' feature, not a plain getX/setX pair)", "field [(if different)] file library record"),
    kw("DLTCHK", "Ignore previously specified validity check"),
    kw("DLTEDT", "Ignore previously specified editing"),
], screenshotDir="screens/field-level/character/database-reference")

cat(fld_lvl, "Error Messages", "ERRMSG/ERRMSGID repeatable, independently-conditioned instances.", [
    kw("ERRMSG", "Error message text", "indicators 'text' more-indicator", repeatable=True),
    kw("ERRMSGID", "Error message by message ID", "indicators msgid file library indicator name", repeatable=True),
], screenshotDir="screens/field-level/character/error-messages")

cat(fld_lvl, "Message ID", "MSGID keyword (distinct from ERRMSGID - system-message-driven, not error-specific).", [
    kw("MSGID", "Message ID, optionally combined with a field/message-ID/message-number", "prefix, identifier [& field/msgid/msgnbr], file, library, indicators"),
], screenshotDir="screens/field-level/character/message-id")

cat(fld_lvl, "Editing Keywords (numeric only)", "Numeric-field output editing.", [
    kw("EDTCDE", "Edit code, optionally replacing leading zeros", "A-D, J-Q, W, Y, Z, 1-9; optional */$"),
    kw("EDTWRD", "Edit word", "'edit word mask'"),
    kw("EDTMSK", "Edit mask", "'mask'"),
], screenshotDir="screens/field-level/numeric/editing-keywords")

cat(fld_lvl, "Constant field additions", "Keyword valid at constant-field level beyond the character-field base set.", [
    kw("HLPID", "Help ID for a constant field", "identifier"),
], screenshotDir="screens/field-level/constant/general")

cat(fld_lvl, "Menu-bar choice - Choice Selection Type", "SNGCHCFLD/MLTCHCFLD plus selection-behavior flags.", [
    kw("SNGCHCFLD", "Single-choice selection field"),
    kw("MLTCHCFLD", "Multiple-choice selection field"),
    kw("*RSTCSR", "Restrict cursor to the choice field"),
    kw("*NORSTCSR", "No cursor restriction"),
    kw("*SLTIND", "Display a select indicator per choice"),
    kw("*NOSLTIND", "No select indicator display"),
    kw("*NUMCOL", "Arrange choices in this many columns", "1-999"),
    kw("*NUMROW", "Arrange choices in this many rows", "1-999"),
    kw("*GUTTER", "Spaces between choice columns", "2-999"),
    kw("*AUTOSLT", "Auto-select the choice on Enter"),
    kw("*NOAUTOSLT", "No auto-select"),
    kw("*AUTOSLTENH", "Auto-select only with an enhanced controller"),
    kw("*AUTOENT", "Enable auto-enter on all displays"),
    kw("*NOAUTOENT", "No auto-enter"),
    kw("*AUTOENTNN", "Auto-enter only when no numeric selection is possible"),
], screenshotDir="screens/field-level/menu-bar-choice/choice-selection-type")

cat(fld_lvl, "Menu-bar choice - Choice Keywords (CHOICE/CHCCTL/CHCACCEL)", "Per-choice-number definitions.", [
    kw("CHOICE", "Selection field choice - text/indicators for one choice number", "choice-number indicators text-field 'text' (deliberately deferred: variable-argument Text-field/Return-field forms, only the literal-text form is modeled)", repeatable=True),
    kw("CHCCTL", "Choice control - conditioning field / message", "choice-number control-field message-id file library", repeatable=True),
    kw("CHCACCEL", "Choice accelerator key text", "choice-number text-field 'text'", repeatable=True),
], screenshotDir="screens/field-level/menu-bar-choice/choice-keywords")

cat(fld_lvl, "Menu-bar choice - Choice Colors and Attributes", "Per-choice-state COLOR/DSPATR.", [
    kw("CHCAVAIL", "Color/attributes for an available choice", "(*COLOR c)(*DSPATR a)", repeatable=True),
    kw("CHCUNAVAIL", "Color/attributes for an unavailable choice", "(*COLOR c)(*DSPATR a)", repeatable=True),
    kw("CHCSLT", "Color/attributes for a selected choice", "(*COLOR c)(*DSPATR a)", repeatable=True),
], screenshotDir="screens/field-level/menu-bar-choice/choice-number-entry")

cat(fld_lvl, "Menu-bar choice - Separator", "The menu-bar's own separator styling.", [
    kw("MNUBARSEP", "Menu-bar separator color/attributes/character", "(*COLOR c)(*DSPATR a)(*CHAR 'c')"),
], sharedWith=["record-level WDWBORDER (same 3-group shape, minus *CHAR default)"], screenshotDir="screens/field-level/menu-bar-choice/separator")

cat(fld_lvl, "Menu-bar choices / Menu-bar separator field wiring", "MNUBARCHC/MNUBARSEP gated on the owning record carrying MNUBAR.", [
    kw("MNUBARCHC", "This field is a menu-bar choice entry point", "choice-number indicators pull-down-record"),
], screenshotDir="screens/field-level/menu-bar-choice/choice-keyword")

total_kw = sum(len(c["keywords"]) for l in data["levels"] for c in l["categories"])
data["meta"]["totalCategories"] = sum(len(l["categories"]) for l in data["levels"])
data["meta"]["totalKeywordEntries"] = total_kw

with open("KEYWORD-INDEX.json", "w") as f:
    json.dump(data, f, indent=2)

print("Wrote KEYWORD-INDEX.json:", total_kw, "keyword entries across", data["meta"]["totalCategories"], "categories")
